package UI;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class MostrarCabealhosNomeeEmailparatabelaTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void mostrarCabealhosNomeeEmailparatabela() {
        driver.get("http://localhost:3000/clients");
        driver.manage().window().setSize(new Dimension(1936, 1056));
        assertThat(driver.findElement(By.cssSelector("th:nth-child(1)")).getText(), is("Nome"));
        assertThat(driver.findElement(By.cssSelector("th:nth-child(1)")).getText(), is("Nome"));
        assertThat(driver.findElement(By.cssSelector("th:nth-child(2)")).getText(), is("E-mail"));
    }
}
